print ("what kind of bear has no teeth?")
print ("")
print ("Press enter for answer")
input ("")
print ("a gummy bear")
print ("")
name=input("what is your name?")
print (f"hello {name} how are you")
input ("")
