name=input("what is your name?")
input('would you like to hear a story?')
print("Ok I need to ask you questions to create your story")
verb1=input("tell me a verb ending in ing")
place=input("tell me a place")
noun1=input("Now tell me a noun")
adjective=input("Tell me an adjective")
verb2=input("Now a verb ending  in ed")
person=input("Now a famous person")
verb3=input("another verb ending with ed")
input("press enter for story")
print("_______________________")
print(f"One day {name} was {verb1} to {place}.")
print(f"On {name}'s way over, there was a big {noun1} in the middle of the road")
print(f"The {noun1} was very {adjective}")
print(f"It didn't seem to bother {name} much so they just {verb2} around it")
print(f"When {name} got to the {place} they saw {person} and started freaking out")
print(f"{name} {verb3} over and asked for a picture")
print(f"{person} completely ignored them")
input("------------")
answer=input("would you like the story to continue? yes or no")
if answer=="yes":
    noun2=input("another noun")
    place2=input("another place")    
    adjective=input("an adjective")
    person2=input("another famous person")
    input("part 2 continued. press enter")
    print(F"{name} chased {person} down the road all the way to {place2}")
    print(f"{person} was very {adjective}")
    print(f"{person} called their bodyguard {person2}")
    print (f"{person2}started fighting {name}")
    print (f"{name}persisted and fought back")
    print (f"{name} won the fight and got an autograph from {person}")

else:
    print("ok byeee")